### ISSUE TITLE
grade-validator-voting: Operate on all contracts

### ISSUE THREAD

**Issue by alpe** [confio/poe-contracts#119]
Currently, grade-validator-voting is limited to contracts that have it as migrator set: ["Validator Proposal contract is not an admin of contract proposed to migrate".to_owned()](https://github.com/confio/poe-contracts/blob/main/contracts/tgrade-validator-voting/src/contract.rs#L115)

This can be a business decision though // tag @ethanfrey

**Comment by maurolacy** [comment]
Fixed (temporarily) by #121.

**Comment by maurolacy** [comment]
Should we be closing as won't-do? The temporary "fix" above was merged to the 0.6.x branch, not main.

In parallel, will open an issue int grade-app, to fix the script that instantiates the tfi contracts.

**Comment by ethanfrey** [comment]
Yes, we can close this. We just need a better setup (as we did / are doing now)
