### ISSUE TITLE
Review TODOs / FIXMEs

### ISSUE THREAD

**Issue by maurolacy** [confio/poe-contracts#138]
TODO:

 - ~~contracts/tg4-stake/src/contract.rs:// TODO: put in cosmwasm-std~~ (Not a big deal. Can be moved to cosmwasm) (**Update**: https://github.com/CosmWasm/cosmwasm/issues/1359)
 - ~~contracts/tg4-stake/src/contract.rs:            // TODO: more detailed compare?~~ (Test improvement)
 - contracts/tg4-stake/src/claim.rs:            // TODO: use `slice::group_by` in place of `Itertools::group_by` when `slice_group_by` is stabilised (Implementation detail. Analyse and resolve) (**Update**: `slice_group_by` is not stable yet)
 - ~~contracts/tgrade-vesting-account/src/error.rs:    // TODO: Temporary error to not panic at unimplemented parts - remove when done~~ (Currently unused. Do we need / want this for Mainnet?) (**Update**: No)
 - ~~contracts/tgrade-vesting-account/src/msg.rs:    // TODO: Add Bond/Unbond implementations~~ (Currently unused. Do we want this for Mainnet?) (**Update**: No)
 - ~~contracts/tg4-group/src/contract.rs:        // TODO: assert the set is proper~~ (Test improvement)
 - ~~contracts/tg4-group/src/contract.rs:            // TODO: more detailed compare?~~ (Test improvement)
 - ~~contracts/tgrade-validator-voting/src/msg.rs:// TODO: add some T variants? Maybe good enough as fixed Empty for now~~ (Outdated. Remove) (**Update**: done)
 - ~~contracts/tg4-engagement/src/contract.rs:            // TODO: more detailed compare?~~ (Test improvement)
 - ~~contracts/tg4-mixer/src/error.rs:    /// TODO: Remove this when we are ready to ensure we finished implementing everything~~ (Unused. Remove) (**Update**: done)
 - ~~contracts/tg4-mixer/src/contract.rs:    // TODO: what events to return here?~~ (Fix / resolve) (**Update**: done. No events returned on instantiate in general)
 - ~~contracts/tg4-mixer/src/contract.rs:    // TODO: multi-test to init!~~ (Test improvement)
 - ~~contracts/tgrade-valset/src/state.rs:    /// TODO: if we allow sub-1 scaling factors, determine if this is pre-/post- scaling~~ (Related to below) (**Update**: Removed)
 - ~~contracts/tgrade-valset/src/state.rs:    /// (TODO: should we allow this to reduce points? Like 1/1000?)~~ (No? Implementation detail. Decide and remove.) (**Update**: No)
 - ~~contracts/tgrade-valset/src/state.rs:    /// TODO: better name to specify this is the Tendermint pubkey for consensus?~~ (Implementation detail. Resolve and remove) (**Update**: done)
 - ~~contracts/tgrade-valset/src/contract.rs~~:            // TODO: signal this is frozen? (Detail. Resolve and remove) (**Update**: done).
 - ~~contracts/tgrade-valset/src/contract.rs:    // TODO: Split it to actual unit tests. This single test has over 100 lines of code and 7 calls~~ (Test improvement)
 - ~~contracts/tgrade-valset/src/contract.rs:    // TODO: Another 7 in 1 test to be split~~ (Test improvement)
 - ~~contracts/tgrade-valset/src/msg.rs:    /// TODO: if we allow sub-1 scaling factors, determine if this is pre-/post- scaling ~~ (Related to below) (**Update**: done)
 - ~~contracts/tgrade-valset/src/msg.rs:    /// (TODO: should we allow this to reduce points? Like 1/1000?)~~ (No? Implementation detail. Decide and remove) (**Update**: done)
 - ~~contracts/tgrade-valset/src/msg.rs:    /// TODO: better name to specify this is the Tendermint pubkey for consensus?~~(Implementation detail. Resolve and remove) (**Update**: done)

FIXME:

 - ~~contracts/tg4-mixer/src/functions.rs:    Decimal::from_i128_with_scale(std_decimal.numerator().u128() as i128, 18) // FIXME: StdDecimal::DECIMAL_PLACES is private~~ (Not a big deal. Can be fixed in cosmwasm-std) (**Update**: https://github.com/CosmWasm/cosmwasm/issues/1361)

**Comment by daniellarita** [comment]
@maurolacy I spoke with Martin about the vesting account contract and it was done as an experiment and is not needed
