### ISSUE TITLE
Add Open Text Proposals

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#15]
The requirement is to have a mechanism to be able to create an Open Text proposal so that a decision is recorded on-chain. Note it is not a binding agreement.

Issue https://github.com/confio/tgrade-app/issues/274 for the UI design. UI coding tickets will follow once the design is in place.

----

We need a new proposal type `Text{}` that has no extra fields besides the existing title and description.

When passed, it saves the title and description in the storage. It takes no other actions. 

These stored proposals can be queried or listed.

Which contracts are affected?

- oversight community
- arbiter pool
- validator voting
- community pool 

This is not included in trusted-circle

To avoid copy paste, a small package for this logic would be nice...

Defining  `execute_text` to handle when passed, and `query_text_proposal` / `list_text_proposals` to view the previously based ones

**Comment by uint** [comment]
I tried implementing something generic in `voting-contract` with type magic :magic_wand: - basically a wrapper around any custom `Proposal` type that enriches it with a `Text` variant. I could get it to serialize transparently with `serde_json`, but not with `serde_json_wasm`.

It's probably solvable with a shared lib by
- doing type wizardry, but implementing a custom serializer/deserializer
- macros
- seeing if https://github.com/rust-embedded-community/serde-json-core/issues/48 can be fixed, maybe? looks related

Either way, it's probably too much. I'm going to do it the easy way for now. Feel free to poke me and take this over if you have cool ideas about how to solve it better.

**Comment by kmw101** [comment]
Front-end issue : https://github.com/confio/tgrade-app/issues/304

**Comment by uint** [comment]
Work done in #27:
* The logic for text proposals was added to the `voting-contract` lib.
* Contracts `tgrade-community-pool` and `tgrade-validator-voting` now implement text proposals.

We can deal with the arbiter pool and OC after a release of `poe-contracts`.

**Comment by ethanfrey** [comment]
Nice work

**Comment by ethanfrey** [comment]
Closed. Follow up in trade-contracts: https://github.com/confio/tgrade-contracts/issues/435
