### ISSUE TITLE
bug when defining the jailing start time

### ISSUE THREAD

**Issue by HannuProd** [confio/poe-contracts#162]
![image](https://user-images.githubusercontent.com/41473010/179719788-52642b5e-d7b3-477c-83c6-7bb528f45593.png)
<img width="1012" alt="Screenshot 2022-07-19 at 10 20 47" src="https://user-images.githubusercontent.com/41473010/179719827-69dfeec2-381a-4812-83ef-58ab58c5eddb.png">

There is a issue with calculating the start time of a jailing proposal:

if the proposal was created at that date (June 30) then it's correct (expiration is 2 weeks later)
Perhaps what's confusing (or plain wrong), is that it should be two weeks since the proposal is executed, not created.
Executed is better. Because that's when the jailing is effectively being enforced.

**Comment by ueco-jb** [comment]
Wrong repository.
