### ISSUE TITLE
[tg4-stake] Contract migration to integrate unbonding of vesting tokens

### ISSUE THREAD

**Issue by daniellarita** [confio/poe-contracts#170]
Steps are:
- ~~Store new tg4-stake on mainnet (version 0.13.0: https://github.com/confio/poe-contracts/releases/download/v0.13.0/tg4_stake.wasm). Register new code_id.~~ (done. new code_id: **14**)
- ~~Create a proposal to migrate the tg4-stake (STAKING) instance (`tgrade17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgsmsjtzp`) to new code_id~~. (done)
- ~~Send the proposal for voting / Ping validators about it~~. (done)
- After proposal is passed, execute it.
- Confirm the new functionality is active and working.

**Comment by maurolacy** [comment]
The proposal text to upgrade the staking contract:

title: `Migrate STAKING contract to code id 14`
description: `Migrate 'STAKING' contract with address 'tgrade17p9rzwnnfxcjp32un9ug7yhhzgtkhvl9jfksztgw5uh69wac2pgsmsjtzp' to code id '14'"

**Comment by maurolacy** [comment]
Proposal parameters:
Quorum: 25%
Threshold: 51%
Allow end early: yes.

**Comment by maurolacy** [comment]
Proposal #1 has passed with 42 Yes votes so far, which allows triggering end early.

**Comment by maurolacy** [comment]
Executed successfully 🎉 .
