### ISSUE TITLE
Fix JailMsg inconsistencies

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#20]
This arose from https://github.com/confio/tgrade/pull/231/files#diff-8db14e10b9ef925e19d3a5efe4e78d5557798674beff468817945ab6a31ec08aR93-R99

When querying [JailingPeriod, we now get](https://github.com/confio/tgrade-contracts/issues/438):

```
"jailed_until":{"forever":{}}
"jailed_until":{"until":"1587556801000000000"}}}
```

However, when we make a [JailMsg](https://github.com/confio/poe-contracts/blob/main/packages/utils/src/jailing.rs#L25-L30) we produce:

```
"duration": "forever"
"duration": {"duration": "1587556801000000000"}
```

The first one is annoying to parse in other languages (easiest if everything is a struct or all strings, don't mix). The second one is a bit of stutter and inconsistent with the Jailing Period.

I propose using the same JSON format for both of them, so JailingDuration would look like:

```rust
#[derive(Serialize, Deserialize, Clone, PartialEq, JsonSchema, Debug)]
#[serde(rename_all = "snake_case")]
pub enum JailingDuration {
    Until(Duration),
    Forever{},
}
```

**Comment by ueco-jb** [comment]
> I believe multiple devs were arguing against the "impurity" of it.

None. At least not in my reviews nor messages that I've read.

**Comment by ethanfrey** [comment]
@ueco-jb good point

**Comment by maurolacy** [comment]
The solution to that would be to use `Forever` internally, but map it to `0` on the API. Just saying. I'm OK with keeping it as it is now, particularly since the maps are already implemented on the other side.
