### ISSUE TITLE
valset: mark "active" validators in ValidatorInfo

### ISSUE THREAD

**Issue by alpe** [confio/poe-contracts#23]
When the `ValidatorInfo` returns a bool value when in the active set then I can set the right status value for GRPC queries without doing a second query on the active set.

Relates to https://github.com/confio/tgrade/issues/124

**Comment by uint** [comment]
@alpe As far as I understand this, `ValidatorInfo` is only provided in `ListActiveValidatorsResponse`, which returns only active validators anyway.

Did you mean adding the bool to `OperatorResponse` in `ListValidatorResponse`?

```rust
#[derive(Serialize, Deserialize, Clone, PartialEq, JsonSchema, Debug)]
pub struct ListValidatorResponse {
    pub validators: Vec<OperatorResponse>,
}

#[derive(Serialize, Deserialize, Clone, PartialEq, JsonSchema, Debug)]
pub struct ListActiveValidatorsResponse {
    pub validators: Vec<ValidatorInfo>,
}
```

**Comment by alpe** [comment]
yes, please add to `OperatorResponse`.
