### ISSUE TITLE
valset: update max_validators

### ISSUE THREAD

**Issue by alpe** [confio/poe-contracts#28]
There should be a way to update the maximum number of validators via gov proposal.
Not sure if OC or validator community would be responsible. 🤷 

[Solution (by Ethan)](https://github.com/confio/poe-contracts/issues/28#issuecomment-1021051702):

1. Add optional arguments to the MigrateMsg. If set, while doing the migration, update the config. This will be used right away to demo in the testnet and as a recovery posibility.

```rust
pub struct MigrateMsg {
  pub min_weight: Option<u64>,
  pub max_validators: Option<u32>,
}
```

2. Add a new variant to [ExecuteMsg](https://github.com/confio/poe-contracts/blob/main/contracts/tgrade-valset/src/msg.rs#L224) - `UpdateConfig`, which just has those two fields for now. It must be gated so only admin can call it and it will update the config and save.

In another issue we expose this to the OC.

**Comment by maurolacy** [comment]
Agree. AFAIK, that's a setting that's defined in genesis, in the Blockchain, so doing that will involve some kind of privileged call from proposal's execution.

**Comment by kmw101** [comment]
I am not sure validators would agree an increase in the maximum as it would have an impact on their revenue? A compelling case would need to be made? Who would champion the increase other than new validators?

The OC are responsible for the allocation of EPs, and Punishing Validators not for the overall governance of the chain.

**Comment by ethanfrey** [comment]
I propose 2 approaches:

1. We add an optional field to MigrateMsg to allow setting this. We can do that when upgrading the contract in the testnet
2. We can add a new entry point on the valset contract that allows the OC to set a new max validators, and an OC proposal to do so.

We can use (1) to update the testnet-3 asap to demo this.
(2) can be a longer term solution and used in testnet-4 (once the app supports this proposal)
