### ISSUE TITLE
[voting-contract] Record proposal creator

### ISSUE THREAD

**Issue by maurolacy** [confio/poe-contracts#31]
Inspired by a similar issue in (private) dao-contracts repo.

Currently the proposal's creator (info.sender) is stored as the first voter on the proposal, and also returned as a Response attribute. Not sure if we want to add the proposer to the proposal, for future queries / reference. Creating this for discussion / tracking.

**Comment by ethanfrey** [comment]
Just one more field on `Proposal` that can be returned during queries, right? Sounds good.
