### ISSUE TITLE
valset: better error message when jail lock not expired

### ISSUE THREAD

**Issue by ueco-jb** [confio/poe-contracts#34]
:shrug: https://github.com/confio/poe-contracts/blob/main/contracts/tgrade-valset/src/contract.rs#L276
Copied from https://github.com/confio/tgrade-contracts/issues/437

**Comment by ethanfrey** [comment]
Let's back port to 0.5.x before closing

(both on main and 0.5.x branch)

**Comment by ueco-jb** [comment]
@ethanfrey done.
