### ISSUE TITLE
Ensure validator is online before adding to the active set

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#36]
When adding a new validator to the validator set, there is no check this validator pub key is valid at all. I could just make garbage ones.

To provide minimal protection against mistake or spam, let's ensure the validator is online before adding them to the active set. We can check they have signed the last block before adding them.

Update: That doesn't work... they cannot sign until they are in... but we need some solution here.

Brainstorm idea: On the first epoch we can transition them to "pending" with minimal voting power (just 1). The next epoch check, for all "pending" validators, we check if they have signed that epoch block and either remove them from the validator set (and jail for 1 day to keep them out, no slashing) if they miss it, or add them with full power if they did sign.

We can think of more ideas here. Not punish for each missing block, but some checks that people are running real validators.

**Comment by ethanfrey** [comment]
Mauro suggests using some off-line report generation that will scan periodically to detect people with poor uptime.

[TgradeQuery::ValidatorVotes](https://github.com/confio/poe-contracts/blob/main/packages/bindings/src/query.rs#L11-L13) will give us access to who signed the current block being processed that can be checked.

Rather than having the blockchain constantly control the active validator set, it controls entry to the set. We can then do more complex analytic tools querying tendermint to decide who is misbehaving, so the OC can jail them,

**Comment by uint** [comment]
So basically for this ticket create an analytics/reporting tool that is entirely off-chain? And the OC will presumably use that to decide who to jail?

Should this live in the `poe-contracts` repo?

**Comment by ethanfrey** [comment]
The continual tool will be off chain.
This issue is about the first check, which will be on chain.

Basically, we have an on-chain gate to enter. 
The continual checks will be another issue in another repo

**Comment by uint** [comment]
Ah, okay!

**Comment by uint** [comment]
> Brainstorm idea: On the first epoch we can transition them to "pending" with minimal voting power (just 1). The next epoch check, for all "pending" validators, we check if they have signed that epoch block and either remove them from the validator set (and jail for 1 day to keep them out, no slashing) if they miss it, or add them with full power if they did sign.

I'm trying to hack at this. Seems interesting. To determine who's signed a block, is [`TgradeQuery::ValidatorVotes`](https://github.com/confio/poe-contracts/blob/main/packages/bindings/src/query.rs#L13) what I want? I guess this is basically a list of who participated in tendermint consensus for the given block?

**Comment by ethanfrey** [comment]
> To determine who's signed a block, is [TgradeQuery::ValidatorVotes](https://github.com/confio/poe-contracts/blob/main/packages/bindings/src/query.rs#L13) what I want? I guess this is basically a list of who participated in consensus for the given block?

Yes. It's a bit tricky as it stores addresses (hashed pub key). I think there are some helpers.

But yeah, we need a 2 step process where people entering the validator set are flagged as "probationary" (with minimal voting power) the first epoch and either promoted to full status or kicked out the second.

**Comment by uint** [comment]
Questions:
* Do we want to expose the information on whether a validator is verified or not via queries?
* If a verified operator leaves the active valset for whatever reason and then re-enters it, do they need to pass verification again? I assume so.
* Is there a reason for 1 voting power specifically? I though we'd need to set the voting power to `min_weight` from the valset cfg for them to be able to vote on a block.

**Comment by ethanfrey** [comment]
> Do we want to expose the information on whether a validator is verified or not via queries?

I don't think so, it will update shortly. But if it makes testing easier, we could add it.

> If a verified operator leaves the active valset for whatever reason and then re-enters it, do they need to pass verification again? I assume so.

I agree, re-verify on re-entry

> Is there a reason for 1 voting power specifically? I though we'd need to set the voting power to min_weight from the valset cfg for them to be able to vote on a block.

1 was my placeholder for "very low". You are right `min_weight` would be more correct (or `min_weight * scaling_factor` or whatever it is the lowest a validator could have)

**Comment by maurolacy** [comment]
Closed in error?

**Comment by ueco-jb** [comment]
> In order to resolve https://github.com/confio/poe-contracts/issues/36, it looks like we need the tgrade-valset contract to use (...)

"resolve" is one of keywords catched by GitHub :)
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by alpe** [comment]
While the original issue was about preventing spam, I believe we need the "signed blocks" data (as floating window) onchain.
IMHO there are at least 4 consumers of signed/missed blocks that we should take into account (random order).
- OC proposal to slash EP
- System to slash stake
- Validators to monitor their system
- Explorers to display this data

The first 2 consumers should be built into the chain so that the logic is predictable and deterministic. A quick solution to fight spam can be slashing stake. This is not hard to automate, quickly executable, effective and easy to communicate with people familiar with running PoS systems.

**Comment by uint** [comment]
> Closed in error?

Oops.

I'm unassigning myself since this isn't a priority right now, but sharing what I dug out.

Turned out we need to:
- [x] Enable `multi-test` and `controllers` to handle `Deps`/`DepsMut` that are generic over the `CustomQuery` type (https://github.com/CosmWasm/cw-plus/pull/652)
- [ ] Make `tgrade-valset` operate on `Deps<TgradeQuery>` rather than `Deps<Empty>` - hopefully this is possible now
- [ ] Should be able to use [`TgradeQuery::ValidatorVotes`](https://github.com/confio/poe-contracts/blob/main/packages/bindings/src/query.rs#L13) now - I think it's going to be something like this:

```rust
deps.querier.query(QueryRequest::Custom(TgradeQuery::ValidatorVotes {}))
```

**Comment by ethanfrey** [comment]
> The first 2 consumers should be built into the chain so that the logic is predictable and deterministic. 

I continue to disagree with you here. I definitely feel it is out of scope of the mainnet launch as this is a hard design question.

How do you consider these floating windows? Is sign at least 200 of the last 1000 blocks really a proper metric? I have seen lots of annoyance with this jailing in the sdk and not that much utility. There is not incentive to get people to come online quickly after the Osmosis epoch, as missing a few hundred blocks is okay. But we cannot always punish for everything.

I think this requires a proper design decision of what any on-chain slashing solution wishes to achieve and how it makes those aims in an effective manner. And that needs time.

I think external tooling and OC voting can be effective. What are the actual cases we are trying to prevent beyond mine of people registering nodes that never existed/have not synced yet?

**Comment by maurolacy** [comment]
My take is, to implement the minimal on-chain check here, as discussed in the description, and leave the rest for either a technical discussion on how to implement the rest on-chain, or off-chain tools.

**Comment by daniellarita** [comment]
@maurolacy has the minimal on-chain check been implemented? cc @HannuProd

**Comment by maurolacy** [comment]
No, not yet. Tom started with it and needed some missing functionality (custom queries). That was then added, but he moved to something else in the mean time. See above for the checklist. That's the current state AFAIK.

**Comment by daniellarita** [comment]
@BirgitPohl who should be assigned to this?
This is a M-L task

**Comment by uint** [comment]
Taking this after discussion with @BirgitPohl.

> No, not yet. Tom started with it and needed some missing functionality (custom queries). That was then added, but he moved to something else in the mean time. See above for the checklist. That's the current state AFAIK.

Yep, that's about it!

**Comment by ks-victor** [comment]
How long do we expect this task take?

**Comment by uint** [comment]
> How long do we expect this task take?

I should have something working on Monday.

**Comment by daniellarita** [comment]
hi @uint what is the status of this?

**Comment by uint** [comment]
> hi @uint what is the status of this?

I didn't manage to finish it on Monday after all, then got busy with design/refinement/communication work on Isotonic side. I'm carving out some time to work on it today, but let's say I'll have something by Monday. Sorry for the bad initial estimation!

**Comment by uint** [comment]
There's a solution in review!
