### ISSUE TITLE
Validator Voting: check `migrate_msg` content to be >0

### ISSUE THREAD

**Issue by ueco-jb** [confio/poe-contracts#46]
Since we allow `migrate_msg` field to be empty, we could actually make it an `Option` to not confuse frontend.
https://github.com/confio/poe-contracts/blob/main/contracts/tgrade-validator-voting/src/msg.rs#L80
```rust
    MigrateContract {
...
        /// encoded message to be passed to perform the migration
        migrate_msg: Option<Binary>,
    },
```

@ethanfrey to confirm

**Comment by ethanfrey** [comment]
No. We do not allow empty slice.
We allow `{}` (which is the serialization of EmptyMsg).

You probably need to add this base64 encoded

We should enforce length > 0
