### ISSUE TITLE
[tgrade-valset] Metadata issues

### ISSUE THREAD

**Issue by maurolacy** [confio/poe-contracts#66]
During #42, noticed a number of relatively small issues with metadata handling in `tgrade-valset`:

- Metadata validation is almost nil. Only moniker is validated, and for minimum length. Let's add validation for max length over all string fields, with some reasonable values. There will be a max length that is enforced by the vm, but that length can be very large for a string field (128 Kb or more).
- Metadata is not validated during instantiation.
- ~~The sender is not validated during metadata update. That means anybody can overwrite the metadata of an operator.~~
- ~~The sender is not validated during validator key registration. That means anybody can register a public key and associated metadata for an operator. Perhaps this is the intended feature, as this registration method can only used for setting a pubkey, not updating one.~~

**Comment by ethanfrey** [comment]
Let's validate all this. Good points.

**Comment by maurolacy** [comment]
> 
> `update()` searches using, which here is `info.sender`. Unless I'm missing something, that means sender may update only his own metadata - if he's already in `operators()` list.

Good. Missed that, was looking for the typical auth pattern I guess.

**Comment by ethanfrey** [comment]
> The sender is not validated during validator key registration. That means anybody can register a public key and associated metadata for an operator. Perhaps this is the intended feature, as this registration method can only used for setting a pubkey, not updating one

Please check this. I think this is handled the same way as update (sender set their own key)

**Comment by ethanfrey** [comment]
> Metadata validation is almost nil. Only moniker is validated, and for minimum length. Let's add validation for max length over all string fields, with some reasonable values. There will be a max length that is enforced by the vm, but that length can be very large for a string field (128 Kb or more).

I think max length of 256 or so should be plenty. You can make it a bit bigger if you think for some fields

**Comment by ueco-jb** [comment]
> Please check this. I think this is handled the same way as update (sender set their own key)

Yup.
```rust
    let pubkey: Ed25519Pubkey = pubkey.try_into()?;
    let operator = OperatorInfo {
...
    match operators().may_load(deps.storage, &info.sender)? {
        Some(_) => return Err(ContractError::OperatorRegistered {}),
        None => operators().save(deps.storage, &info.sender, &operator)?,
    };
```
