### ISSUE TITLE
Add API migration guide

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#70]
So Go and JS clients can easily update with all the naming changes.

Should be human-written docs that capture all changes in a clear way.

**Comment by maurolacy** [comment]
Just some links to migration issues / docs:

This is currently for 0.6.0-rc2. Will add a follow-up for 0.6.0 final when it's ready.

- poe-contracts migration doc: https://github.com/confio/poe-contracts/blob/main/MIGRATING.md
- tgrade-contracts migration doc: https://github.com/confio/tgrade-contracts/blob/main/MIGRATING.md
- Tgrade 0.6.0-rc2 release notes: https://github.com/confio/tgrade/pull/276#issue-1130648700

**Comment by ueco-jb** [comment]
`tgrade-contracts` has its own issue: https://github.com/confio/tgrade-contracts/issues/461

**Comment by maurolacy** [comment]
Changes between 0.6.0-rc2 and 0.6.0 are listed in the changelog file: https://github.com/confio/poe-contracts/blob/main/CHANGELOG.md#v060-2022-02-15
