### ISSUE TITLE
QA Steps to check breakages in CI

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#71]
Let's ensure all 0.6.x updates are 100% compatible with 0.6.0. 

## Acceptance Criteria
- The CI should run `something` to enforce that.
- The main/0.7 tag may include breaks from 0.6. Those need to be noted in human-readable docs. `Where?`
- We can also consider what level of automated support we can/want to use here. Document a set of test an create a collection of issues for that on the board. `Should it be split from this task?`

**Comment by BirgitPohl** [comment]
There are some questions open and need to be clarified in the refinement.
