### ISSUE TITLE
Tools to help build API Migration Guide

### ISSUE THREAD

**Issue by ethanfrey** [confio/poe-contracts#72]
We can start with something like:

`git diff v0.5.3 contracts/*/msg.rs` or maybe schema diffs

some tool to get the raw info of what changed, then we can hand-make before/after examples that highlight the changes

**Comment by maurolacy** [comment]
We could be doing this easily if the schema were part of the repo. But we removed it a while ago.

Working on a script to generate the schema locally over the different tags / branches.
